### ISSUE TITLE
store a list of mutations for reporting

### ISSUE THREAD

**Issue by llogiq** [llogiq/mutagen#1]
The plugin has all it needs to generate a list of mutations, e.g. "insert early `return default()` at foo.rs, line 32, column 5." or "changing < to <= at too.rs, line 34, column 9".

The plugin should write out the list for later reporting of surviving mutations.

**Comment by llogiq** [comment]
Currently I store the mutation descriptions in a `Vec`, but this should be easy to change to write into a file instead. The only open question is where to put it. We may have a crate root from the `ExtCtxt`, perhaps somewhere below `target/`?

**Comment by hmvp** [comment]
Would it be an idea to generate a function that would end up in the resulting binary that can be called from the test harness/mutagen harness which would output the info? Or store it in the resulting binary in some other way?

**Comment by llogiq** [comment]
I don't think we need to go to such lengths; we can assume normal Rust project layout. Just create a `target/mutagen/` folder and put the mutation list there. The test runner will be called in that project root and so can just bail if the mutation list isn't there.
