### ISSUE TITLE
Is one global mutator variable enough?

### ISSUE THREAD

**Issue by hmvp** [llogiq/mutagen#13]
From what I gather from the code the plugin replaces all kinds of constructs with a match that 'mutates' based on one global number. I can image that this will lead to situations where specific code paths are not triggered because a similar mutation in two places is always the same mutation

For example: In this example both ifs will be flipped by the if mutation at the same time resulting in a working function..
```
fn contrived_example(condition: bool) -> u8 {
   let result = if !condition { true } else { false };
   if result { 1 } else { 0 }
}
```

I am not sure if this is actually harmful for the goal of the project. And I don't know how to do it differently since a variable per mutation does not really make sense.

**Comment by llogiq** [comment]
No, we only swap out one thing at a time. The mutation count keeps track of that, so it should suffice.

**Comment by hmvp** [comment]
After looking at the code some more I see what is happening. I agree that it should work as it is. I don't thinks swapping more than one thing at a time is actually desired and it does not do that indeed.
