### ISSUE TITLE
Issue with binop module during cargo test

### ISSUE THREAD

**Issue by twk** [llogiq/mutagen#132]
I'm getting this error after integrating mutagen with a big rust project at work and running `cargo test`.  I apologize I can't debug this more, but I'm pretty new at Rust.

```
error[E0583]: file not found for module `binop`
  --> vendor/mutagen-plugin-0.1.1/src/lib.rs:27:5
   |
27 | mod binop;
   |     ^^^^^
   |
   = help: name the file either binop.rs or binop/mod.rs inside the directory "vendor/mutagen-plugin-0.1.1/src"

error: aborting due to previous error

For more information about this error, try `rustc --explain E0583`.

```

**Comment by twk** [comment]
This seems fixed if I use the latest version from github, fwiw.

**Comment by llogiq** [comment]
yeah, we need a new release, but not before we fix the latest breakage.

If you are OK with it, I'd like to close this. We'll have it fixed eventually.

**Comment by twk** [comment]
Sounds good!
