### ISSUE TITLE
Helper library: Allow to set initial mutation count

### ISSUE THREAD

**Issue by llogiq** [llogiq/mutagen#15]
This should probably just be putting the MU into a `lazy_static` and setting the value by parsing an environment variable.

**Comment by creativcoder** [comment]
Hi, @llogiq I'll take this

**Comment by llogiq** [comment]
It's all yours! :smile:

**Comment by llogiq** [comment]
@creativcoder Do you need any pointers on where to start?

**Comment by creativcoder** [comment]
Yes please :)

**Comment by llogiq** [comment]
In the helper library (`src/lib.rs`), there is a `static MU : Mutagen` global static. As it is, it cannot do initialization that would require runtime code. To change this, we'll use the [lazy_static](https://docs.rs/lazy_static/1.0.0/lazy_static/) crate (which means you'll have to add this in the helper library's `Cargo.toml` as a dependency. Be sure to check out the lazy_static docs link for usage instructions.

Now we can execute code to initialize our `Mutagen`, we can use [`std::env::var(..)`](https://doc.rust-lang.org/std/env/fn.var.html) to get the number as a `Result<String, VarError>`. On error, just set the count to `0` and `str::parse` the string otherwise.

Ping me if you need further instructions.
