### ISSUE TITLE
Cargo can't find version 0.2.0

### ISSUE THREAD

**Issue by julienJean99** [llogiq/mutagen#159]
Hi,

I would like to add mutation testing for a project that just started so i added
```
[dev-dependencies]
mutagen = "0.2.0"
```

to my cargo.toml like the README says.

My cargo run's `cargo 1.42.0-nightly (86134e766 2019-12-23)` but without adding any test
I am having this error:

```
error: failed to select a version for the requirement `mutagen = "^0.2.0"`
  candidate versions found which didn't match: 0.1.2, 0.1.1, 0.1.0
  location searched: crates.io index
```
every time I try to do anything.

Do I revert back to 0.1.2 (Error in the README) or is my cargo out of date and can't find the latest version/how do I make it find the latest version?

**Comment by power-fungus** [comment]
`mutagen-0.2` is currently not released on `crates.io`. Currently you could use `mutagen = {git = "https://github.com/llogiq/mutagen"}`

**Comment by julienJean99** [comment]
thank you for the **very** quick response!

This should perhaps be sayed in the readme.

**Comment by llogiq** [comment]
I'll push out a release before the weekend.

**Comment by power-fungus** [comment]
@llogiq please review the used version-tags. I did bump the version of `cargo-mutagen` to `0.2.1` after adding the `--features` flags. Feel free to revert that if you like
