### ISSUE TITLE
Mutation: Switch arguments of same type

### ISSUE THREAD

**Issue by llogiq** [llogiq/mutagen#16]
The plugin already has the analysis. There are but two wrinkles to take care of:

* [ ] It may make a difference if the args are taken by ref or by value, the analysis pass doesn't take that into account yet
* [ ] we should take care not to issue the same switch twice. This could probably be done easily by filtering the argument pairs so only pairs where the first name compares lower than the last one are switched.

**Comment by rajcspsg** [comment]
@llogiq Anybody working on this. Otherwise I will interested in taking this issue.

**Comment by llogiq** [comment]
It's yours! Do you need any pointers where to start?

**Comment by rajcspsg** [comment]
Thanks @llogiq. Since I'm self learning rust anything will be really helpful!!!

**Comment by llogiq** [comment]
If you compile the plugin, you get a warning about the unused `interchangeables` variable, and this is exactly the part where we want to use it. But first, we'll have to fix the two snags I mentioned above, and this is in the `start_fn(..)` function.

First, I have made a mistake to unpack the mutatbility from the `BindingMode` – we should just put the `BindingMode` itself in the key. Second, we should change the filter for our `interchangeables` value to only include names greater than the key. This will get rid of duplicates.

Once we've done this, it is simply a matter of iterating over the map and its values and inserting a `let (a, b) = if mutagen::now($n) { (b, a) } else { (a, b) };` statement in the `fold_first_block` function.

Ping me if you need further directions.

**Comment by rajcspsg** [comment]
Thanks @llogiq . I will go let you know if any help is needed.

**Comment by rajcspsg** [comment]
hey @llogiq . I get below error error when trying compile and test mutagen.

```$ cargo build
   Compiling mutagen v0.1.0 (file:///Users/rajkumar.natarajan/Documents/Coding/mutagen)
error: `std::sync::atomic::AtomicUsize::new` is not yet stable as a const fn
  --> src/lib.rs:46:39
   |
46 | pub static MU: Mutagen = Mutagen { x: AtomicUsize::new(0) };
   |                                       ^^^^^^^^^^^^^^^^^^^
   |
   = help: in Nightly builds, add `#![feature(const_atomic_usize_new)]` to the crate attributes to enable

error: aborting due to previous error

error: Could not compile `mutagen`.

To learn more, run the command again with --verbose.```
Any idea on this?

**Comment by llogiq** [comment]
Ah, it appears you try to compile on stable. My bad, this only works on nightly. However, changing this to use `lazy_static` will make the helper library work on stable, anyway. So while it may be a good idea to `rustup toolchain install nightly`, this is not needed for now. Follow the lazy_static docs.

**Comment by rajcspsg** [comment]
@llogiq - Thanks for suggestion. I have added lazy_static and now my code  build and test is successful. Can I send a separate PR for this.

**Comment by llogiq** [comment]
Oops, I mixed up two issues, @creativcoder wanted to do the `lazy_static` thing. You will need to compile the plugin, which needs a nightly rustc. I hope this is no problem.

**Comment by rajcspsg** [comment]
@llogiq - Below the build and test command output, I didn't warning for `Interchangables`.

```rajkumar@linux-7owj:~/Coding/Rust/mutagen> cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling lazy_static v1.0.0
   Compiling mutagen v0.1.0 (file:///home/rajkumar/Coding/Rust/mutagen)
    Finished dev [unoptimized + debuginfo] target(s) in 0.41 secs
rajkumar@linux-7owj:~/Coding/Rust/mutagen> cargo test
   Compiling mutagen v0.1.0 (file:///home/rajkumar/Coding/Rust/mutagen)
    Finished dev [unoptimized + debuginfo] target(s) in 0.70 secs
     Running target/debug/deps/mutagen-ace02fef7948a774

running 2 tests
test tests::ne_mutation ... ok
test tests::eq_mutation ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests mutagen

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out```

Below is my nightly rust installation details -

```rajkumar@linux-7owj:~/Coding/Rust/mutagen> rustc --version
rustc 1.26.0-nightly (29f5c699b 2018-02-27)```

**Comment by llogiq** [comment]
No, you're good to go. Run `cargo check` in the `plugin` subdirectory.

**Comment by rajcspsg** [comment]
@llogiq 

Looks like I need more support on this.

For the `BindingMode` thing that you mentioned I have changed the code as below.

```
fn get_pat_name_mut(pat: &Pat) -> Option<(Symbol, BindingMode)> {
    if let PatKind::Ident(mode, i, _) = pat.node {
        //Some((i.node.name, match mode { BindingMode::ByRef(m) | BindingMode::ByValue(m) => m }))
        Some((i.node.name, mode))
    } else {
        None
    }
}
```

Is this correct?

For filtering  the interchangeables value to only include names greater than the key, I should update the filter condition [here](https://github.com/llogiq/mutagen/blob/master/plugin/src/lib.rs#L135), correct?

**Comment by llogiq** [comment]
Exactly! Very good, you're on the right track. While you're at it, it's probably a good idea to move the `.filter(_)` before the `.cloned()`, to avoid needless allocations.

**Comment by rajcspsg** [comment]
@llogiq 

Looks like the tests in the current master is failing.

```
> cargo test
   Compiling mutagen v0.1.0 (file:///home/rajkumar/Coding/Rust/mutagen)
    Finished dev [unoptimized + debuginfo] target(s) in 0.80 secs
     Running target/debug/deps/mutagen-ace02fef7948a774

running 2 tests
test tests::ne_mutation ... FAILED
test tests::eq_mutation ... FAILED

failures:

---- tests::ne_mutation stdout ----
        thread 'tests::ne_mutation' panicked at 'assertion failed: `(left == right)`
  left: `false`,
 right: `true`', src/lib.rs:306:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- tests::eq_mutation stdout ----
        thread 'tests::eq_mutation' panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`', src/lib.rs:288:9


failures:
    tests::eq_mutation
    tests::ne_mutation

test result: FAILED. 0 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--lib'

```

Also, I've changed the code for interchanges as below. Is that correct.

`typeargs[&mut_ty].iter().filter(|a| a >= &&arg).cloned().collect(),`

**Comment by llogiq** [comment]
Yeah, I've seen it, don't worry about it, I'm going to fix the tests soon. And yes, the change to `interchangeables` looks good. Now you only need to apply them, by inserting a ` let ($a, $b) = if mutagen::now($n) { ($b, $a) } else { ($a, $b) };` (where $a, $b are the identifiers) statement before the first block's statement (in `fold_first_block`, look for `TODO`).

**Comment by llogiq** [comment]
Hi there! Looks like we've made other progress. Probably you need to rebase or merge our changes. Are you OK with opening a work-in-progress PR so we can see and discuss your changes? I know that each git rebase is a hassle, and I want you to succeed with finishing this issue.

**Comment by rajcspsg** [comment]
@llogiq - I'm sorry for the delay. I have created PR for this issue. Still I couldn't complete the last part for `TODO` in `fold_first_block`.
I get error `error: expected pattern, found `$``. Could you please help on this.

**Comment by llogiq** [comment]
No need to be sorry. I don't want to hurry you, I just want to keep you from getting stuck. So thanks for  setting up the PR, I will comment on it directly further. :+1:
