### ISSUE TITLE
With the release of Rust 1.45, will this work with stable?

### ISSUE THREAD

**Issue by itamarst** [llogiq/mutagen#168]
Thanks!

**Comment by power-fungus** [comment]
Currently, we use 

```rust
#![feature(proc_macro_span)]
#![feature(specialization)]
```

Specialization *could be omitted* by dropping mutations that depend on it. (I recall some post about specialization-emulation via auto-deref, but using that strategy that was not my priority)

Proc macro span is required to display where the mutations were made.

Dropping any of the features would undermine the usefulness of mutagen (in my opinion).

**Comment by itamarst** [comment]
Thanks, that was informative.
