### ISSUE TITLE
`mutagen` does not respect `target` directory configuration 

### ISSUE THREAD

**Issue by tcharding** [llogiq/mutagen#191]
If one has the following `~/.cargo/config` file
```
[build]
target-dir = "/home/<user>/.cache/cargo"
```

I would expect `mutagen` to put artifacts in the configured directory however `target/` inside the crate being tested is used.

**Comment by samuelpilz** [comment]
How does this global target directory behave? Is this shared across all crates? How would you expect `<target>/mutagen` to be structured?

**Comment by llogiq** [comment]
We probably currently join the target directory manually, thus overriding any `TARGET_DIR` the user might have set. Haven't had a look at that part of the code for quite some time.

**Comment by samuelpilz** [comment]
I have an idea on how to solve this. But I am intrigued about the semantics of a shared target folder.

**Comment by tcharding** [comment]
Continuing the example above, perhaps we could put all the report directories in `~/.cache/cargo/mutagen/<crate>/`? We would also need the stuff that is now in `target/mutagen/`.

**Comment by llogiq** [comment]
I think we just have [`const DEFAULT_MUTAGEN_DIR: &str = "target/mutagen";`](https://github.com/llogiq/mutagen/blob/a6377c4c3f360afeb7a287c1c17e4b69456d5f53/mutagen-core/src/comm/mutagen_files.rs#L9), which completely ignores any target dir settings. So if we change this to follow `TARGET_DIR` (and add `mutagen`) in line 29, this should fix it.

**Comment by samuelpilz** [comment]
Unfortunately, the proc-macro has no access to the `TARGET_DIR` variable (at least in my tests).

@tcharding, why would you prefer `~/.cache/cargo/mutagen/<crate>/` over `~/.cache/cargo/target/mutagen/<crate>/`? Mutagen considers its files as "generated project artifacts" similar to benchmark results (which are also stored in the target folder, right?)

**Comment by tcharding** [comment]
Oh if can't use `TARGET_DIR` then I'd leave it in the crate directory. Feel free to close this issue if that is the case. Thanks for looking into it.

**Comment by llogiq** [comment]
We may want to ask the dev-tools team for a solution.

**Comment by samuelpilz** [comment]
Yes, it would be quite nice to have access to this env var in a proc-macro. In fact, there are already several env vars set: (see [cargo reference](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates)

My workaround to solve this: 
* Have the runner query cargo for the target dir. 
* Set the target dir as an env-var for compilation
* ensure the code under test is recompiled, triggering a re-run of the proc-macros, having now access to this env var

**Comment by llogiq** [comment]
Following input from the dev-tools team, we should avoid writing outside `$OUT_DIR`, no matter what target dir is set to. Rust may in the future get some sandboxing functionality to make writing outside `$OUT_DIR` a hard error. So while I'm sympathetic to @tcharding's request, I'm afraid we would need to rewrite mutagen to not be a proc macro first.

**Comment by tcharding** [comment]
No worries, thanks for your effort!

**Comment by samuelpilz** [comment]
> Rust may in the future get some sandboxing functionality

this would be amazing, but I believe that that effort would include some structured way to communicate to the outside (even write-only).
