### ISSUE TITLE
False positive for `<`

### ISSUE THREAD

**Issue by tcharding** [llogiq/mutagen#192]
Awesome tool, thanks!

When a function has logic that uses a less than operator but the result is the same at the boundry then we get a false negative when we mutate at the boundry.

## Example
```rust
#[cfg(test)]
use mutagen::mutate;

#[cfg_attr(test, mutate)]
pub fn abs(x: i32) -> u32 {
    if x < 0 {
        return (0 - x) as u32;
    }

    x as u32
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn abs_possitive() {
        assert_eq!(abs(10), 10);
    }

    #[test]
    fn abs_negative() {
        assert_eq!(abs(-10), 10);
    }

    #[test]
    fn abs_zero() {
        assert_eq!(abs(0), 0);
    }
}
```

## False positive
```bash
Total mutations: 6

Run 2 tests
/home/tobin/.cache/cargo/debug/deps/play-7fd5644562bffd4f ... ok (NOTHING COVERED)
/home/tobin/.cache/cargo/debug/deps/play-f349b961149a08a8 ... ok (6/6 covered)

Mutations covered: 6/6

Test 6 Mutants
1: lit_int, replace `0` with `1`, at src/lib.rs@6:12-6:13(fn abs) ... SURVIVED
2: binop_cmp, replace `<` with `<=`, at src/lib.rs@6:10-6:11(fn abs) ... SURVIVED
3: binop_cmp, replace `<` with `>=`, at src/lib.rs@6:10-6:11(fn abs) ... killed
4: binop_cmp, replace `<` with `>`, at src/lib.rs@6:10-6:11(fn abs) ... killed
5: lit_int, replace `0` with `1`, at src/lib.rs@7:17-7:18(fn abs) ... killed
6: binop_num, replace `-` with `+`, at src/lib.rs@7:19-7:20(fn abs) ... killed

SURVIVED
    src/lib.rs
            2/6(33.33%) mutants survived
        1: replace `0` with `1` at 6:12-6:13(fn abs)
        2: replace `<` with `<=` at 6:10-6:11(fn abs)

6 generated mutants
4(66.67%) mutants killed, 0(0.00%) by timeout
2(33.33%) mutants SURVIVED, 0(0.00%) NOT COVERED
Total time: 10s
```

**Comment by tcharding** [comment]
perhaps this example is better (gives a single false negative)
```rust
#[cfg_attr(test, mutate)]
pub fn abs(x: i32) -> u32 {
    if x < 1 {
        return (0 - x) as u32;
    }

    x as u32
}
```

**Comment by Kixunil** [comment]
Did you mean false positive?

**Comment by llogiq** [comment]
If you have a don't care state, this mutant cannot be killed. This is a known fact and should not worry you.

Perhaps document the fact in your test suite?

**Comment by tcharding** [comment]
Ok, no worries - thanks very much.

**Comment by tcharding** [comment]
I just had an idea, would it be possible to use an attribute similar to how we use `#[rustfmt::skip]` to tell mutagen to not mutate a line (or scope)?

Continuing the example above
```rust
#[cfg_attr(test, mutate)]
pub fn abs(x: i32) -> u32 {
    #[mutagen::skip]
    if x < 1 {
        return (0 - x) as u32;
    }

    x as u32
}
```

FTR I have no idea how attributes are implemented so have no idea if this is possible of how much work it is.

**Comment by llogiq** [comment]
Yes, that should be possible.

**Comment by tcharding** [comment]
I'd like to help out with this if that would be useful (mainly I just want the feature :) but I don't know anything about proc macros. Do you have any tips for an approach to use please? I looked at the `MutagenTransformerBundle` and see that it implements `Fold` which seems to handle each `syn::Item` - so I guess if the transformer bundle held state on whether it had seen a `mutate::skip` attribute we could check that state in each of the `Fold` trait methods. Is this at all feasible or am I totally off track?

A totally different idea is to try and work out how `rustfmt::skip` is implemented but a brief look at `rustfmt` code left me lost.

Thanks

**Comment by llogiq** [comment]
You can just look into the attributes of an Item and just return the item if a `mutate::skip` is present or set a flag to avoid all mutations.

**Comment by tcharding** [comment]
Sweet, thanks man.

**Comment by tcharding** [comment]
I spent three hours and made absolutely zero progress - leaving it for someone more knowledgeable than myself. Thanks for the pointer though.
