### ISSUE TITLE
programmatically run the test suite

### ISSUE THREAD

**Issue by llogiq** [llogiq/mutagen#2]
The easiest way is to run `cargo test` with the mutagen plugin, then run the resulting binary for each mutation, giving the mutation number to the test binary as an environment variable.

* [x] compile tests with plugin
* [x] read mutation list, call test binary with mutation count

**Comment by Keirua** [comment]
From what I understand, in a first step that sounds like a shell script, right ? It seems to depend on https://github.com/llogiq/mutagen/issues/15

**Comment by llogiq** [comment]
Yes. That and finding out (or setting) the correct name for the test binary.

**Comment by llogiq** [comment]
I asked /r/rust, `cargo test --no-run --message-format=json` will output the name of the executable, among other things.
