### ISSUE TITLE
Mutation: Use unsafe code to generate 'valid' values

### ISSUE THREAD

**Issue by hmvp** [llogiq/mutagen#20]
The compiler makes it a bit harder to replace certain statements. Can we use unsafe code like mem::transmute to force some arbitrary value into the desired type? This should work for sized types where all bitpatterns are valid (enums for example won't work)

**Comment by llogiq** [comment]
When going unsafe we could alway use `mem::uninitialized()`, but again, this requires knowing about the type, and at that point, we can probably construct one without unsafe code. I think we will need to integrate RLS at some point to find out more about the types.

**Comment by llogiq** [comment]
I'm going to close this for now. We are asking people not to mutate unsafe code, so introducing it on our own would be quite reckless. Also, inserting uninitialized memory could lead to undefined behavior, which allows the compiler to change the behavior of the code under mutation, so MUTATION_COUNT=0 would no longer do the same as the original test – we must not allow this to happen.
