### ISSUE TITLE
Apply mutations recursively

### ISSUE THREAD

**Issue by gnieto** [llogiq/mutagen#32]
Currently the plugin is not applying rules recursively. For example, if the following snippet needs to be mutated:

```
if count == 2 {
    // Some
}
```

Generates the following code:

```
    if mutagen::t(
        count == {
            if mutagen::now(29usize) {
                2 + 1
            } else {
                {
                    if mutagen::now(28usize) {
                        2 - 1
                    } else {
                        2
                    }
                }
            }
        },
        25usize,
    ) {
        // Some!
    }
```

But if the snippet is:

```
    if (count == 2) {
        // Some!
    }
```

The generated code will be:

```
    if mutagen::t((mutagen::eq(|| count, || 2, 28usize)), 25usize) {
        // Some!
    }
```

On the first snippet, the "if" and the "off-by-one" mutations are applied.
On the second one, the "if" and the "eq" are applied.

Note that the plugin should be able to apply the 3 mutations on any of the cases. This should be as easy as change the calls to `fold::noop_fold_expr` to `self.fold_expr` instead. This should be changed on the `fold_expr`.

**Comment by llogiq** [comment]
Ah, I see `noop_fold_expr(expr, self)` calls `self.fold_expr(_)` on all *sub*expressions of `expr`. So we should indeed issue `self.fold_expr(_)` on all sub-expressions of whatever we fold directly.
