### ISSUE TITLE
publish to crates.io?

### ISSUE THREAD

**Issue by yoshuawuyts** [llogiq/mutagen#33]
Heya! I was looking to try this out, but it's not available on crates.io. I was wondering if you'd mind publishing it, so it becomes easier to try out on my own projects. Thanks!

**Comment by llogiq** [comment]
Sure, will do when I get my PC online.

**Comment by yoshuawuyts** [comment]
@llogiq yay, thanks!

**Comment by llogiq** [comment]
You're welcome. For now, the process is very rough around the edges...no really, it's all edges for now. :slightly_smiling_face:
