### ISSUE TITLE
&& , || must evaluate their first, == , != both arguments

### ISSUE THREAD

**Issue by llogiq** [llogiq/mutagen#34]
In this example:

```rust
fn foo() -> usize { 2 }
fn bar() -> usize { 23 }

fn blubb() -> usize {
    let mut value;
    if ({ value = foo(); value > 5 }) || ({ value = bar(); value < 5 }) {
        value + 1
    } else {
        42
    }
}

fn main() {
    println!("{}", blubb());
}
```

We cannot mutate the `||` to `true` or `false`, because then `value` would not be set, so the compiler will bail. This also means we cannot in general rely on closures to defer actions, because of the side effects / returns we might lose. Solving this for `||` and `&&` is perhaps not trivial, but workable:

For example, `x || y` can be mutated to:

```rust
(match ($x, mutagen::diff($n)) {
    (_, 0) => false,
    (_, 1) => true,
    (x, 2) => x,
    (x, 3) => !x,
    (x, n) => x || ($y) == (n != 4),
})
```

**Comment by hmvp** [comment]
OTOH this is very bad practice and I hope there is at least a clippy lint warning for this..

If you do this in C all coding standards checkers will scream at you...

Does it make sense to have a flag to enable more mutations at the cost of requiring sane code?

**Comment by llogiq** [comment]
I certainly agree this particular example is malicious, however I don't want to be opinionated here if I can help it.

1. The user may not own the tested code
2. There may be valid reasons for the code to look like this. It may even be hidden to the user via macros.

Also in this instance it is easy enough to work around.
