### ISSUE TITLE
Add mutation codes

### ISSUE THREAD

**Issue by llogiq** [llogiq/mutagen#53]
Currently the mutation descriptions are mostly nice to read, but quite wordy and not very machine-understandable. In order to e.g. allow filtering mutations, we should add a unique mutation code per mutation type.

This is fairly easy: Just prepend the code before each message in `add_mutations` in the plugin. The hard part is, as usual, naming things.

**Comment by manaskarekar** [comment]
Do you think it's better to add a new field to add_mutation, something like 'mutation_id' or simply prepend a code to the description?

Perhaps we could maintain an enum of valid mutation_ids, or a simple list, but not sure about this.

**Comment by llogiq** [comment]
I'm a fan of 'the simplest thing that will possibly work', so prepending the plain strings to the description sounds like a good plan to me.

Also I'd like the ID/code to relate to each mutation number, which is not the same as the change in the code we added. Note that we often add multiple mutations at once, and most of them are conceptually equal. So e.g. I'd like to have a code for 'REPLACE_WITH_TRUE' etc.
