### ISSUE TITLE
Runner - Support for testsuites with more than one executable

### ISSUE THREAD

**Issue by gnieto** [llogiq/mutagen#55]
At the moment, the runner finds only one test executable.

The method `compile_tests` compiles the test and returns a single `PathBuf`, but it should return a vector of them, and execute each of the found test binaries. Note that we are early-returning when we find the first path.

With this change, mutagen will be able to run on projects which has both unit, integration and doc tests.

**Comment by rajcspsg** [comment]
@gnieto  @llogiq - I would like to work on this issue. can I take this one?

**Comment by llogiq** [comment]
Sure thing! Be aware that @gnieto's current PR also changes the runner, so one of you may run into merge conflicts. Such is life :smile:

**Comment by llogiq** [comment]
I've merged it, so you can pull and work on this without (hopefully) any interference. I think the first order of action is to run `cargo test --no-run --message-format=json` manually and see what it outputs for projects with doc tests, local unit tests (within the module) and integration tests (in the `tests/` subdirectory). In particular, we want to distinguish test running executables from other build artifacts.

**Comment by hmvp** [comment]
Also be aware that AFAIK doctests don't end up in a actual binary. So we might need to do something special for those...

**Comment by llogiq** [comment]
Really? Because I get a test binary for my doctests (tested with [optional](https://github.com/llogiq/optional)), named after the library. I'm not sure about bin crates, though.

**Comment by llogiq** [comment]
@rajcspsg it appears @rleungx has already started this one.

**Comment by rajcspsg** [comment]
@llogiq okay then I will take different one.

**Comment by hmvp** [comment]
@llogiq Are you sure it includes the doctest? From what I can see is that `cargo test` first runs all the binaries for each crate and then runs `Doc-tests <crate-name>` but that does not generate runnable binaries.. See also https://github.com/codecov/example-rust

**Comment by llogiq** [comment]
@hmvp You're right – I somehow overlooked that. This calls `rustdoc --test ..` (you can easily get this with `cargo test --verbose`). We need to be able to issue this call and distinguish between doc tests and other tests.

Also I just found out there is another issue lurking here: tests are not exactly matched. So if we have the tests `a`, `aa`, `aaa`, `aaaa`, issuing `<test-binary> test a` will call all of them. Judicious use of `--skip <name>` (an undocumented libtest feature) should help here, but this means we need to identify test names which are prefixes of others.
