### ISSUE TITLE
Mutation: Introduce off-by-ones in for loops

### ISSUE THREAD

**Issue by llogiq** [llogiq/mutagen#6]
This requires finding for loops over ranges and introducing an iterator that will skip the first, the last
or every element (depending on mutation number) of the wrapped iterator / IntoIterator. We know that the
value has an `IntoIterator` impl because it's used in a `for` loop.

This has two interesting subtasks:

* [ ] create the mutating iterator
* [ ] add the mutation to the plugin

**Comment by gnieto** [comment]
This was closed with: https://github.com/llogiq/mutagen/pull/73
