### ISSUE TITLE
Mutate while let Some(_) loops

### ISSUE THREAD

**Issue by llogiq** [llogiq/mutagen#65]
We can mutate `while let Some($ident) = $expr { $block }` loops to extend `$expr` to `if ::mutagen::now($n) { None } else { $expr }`. We already have similar extensions for `if`s, so this should be simple to implement.

**Comment by rajcspsg** [comment]
@llogiq I'm back :-) . Shall I take this issue?
Also, please provide inputs for me to start.

**Comment by llogiq** [comment]
@rajcspsg  It's all yours!

The `fold_expr  function needs another match arm for `ExprKind::WhileLet`. This will give you access to the condition expression, which we subsequently mutate (see the other code for how to do it), the block also needs to be folded using `self.fold_block(..)`.

**Comment by rajcspsg** [comment]
@llogiq _ I started doing changes. When I do changes I tried `cargo build` and I got below error.

```
error[E0277]: the trait bound `usize: std::convert::From<u128>` is not satisfied
   --> src/lib.rs:900:20
    |
900 |             return usize::try_from(val).ok();
    |                    ^^^^^^^^^^^^^^^ the trait `std::convert::From<u128>` is not implemented for `usize`
    |
    = help: the following implementations were found:
              <usize as std::convert::From<u16>>
              <usize as std::convert::From<u8>>
    = note: required because of the requirements on the impl of `std::convert::TryFrom<u128>` for `usize`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.

```

I see rust document has `TryFrom` implemented for `usize` [here](https://doc.rust-lang.org/std/primitive.usize.html#impl-TryFrom%3Ci128%3E).

My rustc version is 

```
$ rustc --version
rustc 1.26.0-nightly (06fa27d7c 2018-04-01)

```

Any idea I get this error?

**Comment by gnieto** [comment]
@rajcspsg I think this was fixed on: bbf53d47cd6b4c897458343d47efcec9dd9d342b

I guess that pulling from master and rebasing your branch should fix the error.

**Comment by rajcspsg** [comment]
@gnieto - Yeah I rebase with upstream and I'm able to do clean build.

**Comment by llogiq** [comment]
After some [research and experimentation](https://llogiq.github.io/2018/05/30/inop.html) I've found this to be impossible to make work in the general case. Sorry!
