### ISSUE TITLE
Found some issues with opportunistic mutations

### ISSUE THREAD

**Issue by gnieto** [llogiq/mutagen#77]
I've found some issues on some mutated code since the introduction of opportunistic mutations. 
've opened a PR: https://github.com/llogiq/mutagen/pull/76 with a couple of minimal examples that can be used to debug the issue.

**Comment by llogiq** [comment]
I have a solution for the `Shl`/`Shr` problem, see https://stackoverflow.com/questions/49730693/why-is-stdopsshlshl-not-equal-to/49751227#49751227

**Comment by llogiq** [comment]
So this should be closed now that the shifts are fixed.
