### ISSUE TITLE
Add timeout when executing mutated tests

### ISSUE THREAD

**Issue by gnieto** [llogiq/mutagen#88]
When running mutated code, we may lead to infinite loops. Even if we implement https://github.com/llogiq/mutagen/issues/23 or https://github.com/llogiq/mutagen/issues/24 it would be nice to have timeouts when running tests.

We could use [structopt](https://crates.io/crates/structopt) to be able to configure this timeout.

**Comment by llogiq** [comment]
I'll be taking this.
