### ISSUE TITLE
Extend `int_constant_can_add_one` to cope with other non-maximal consts

### ISSUE THREAD

**Issue by llogiq** [llogiq/mutagen#93]
In [`plugin/src/lib.rs`, line 621](https://github.com/llogiq/mutagen/blob/dffca47b7957cfce47d136436a21dde63ed2dbf6/plugin/src/lib.rs#L621), we only check against u8::MAX, however this doesn't tell us the whole truth. If our number is indeed *greater* than u8::MAX, we can assume that the type is at least 16 bit, so we should return `true` unless the given value is equal to *any* MAX value.

This can be done most easily by creating a static array of MAX values and using `slice::contains` to check for any value. I'm up for mentoring if anyone wants and/or needs it.

**Comment by rleungx** [comment]
Can I take this one?
